services:
  db:
    image: postgres:15-alpine
    container_name: nexus_db
    environment:
      POSTGRES_DB: nexusdb
      POSTGRES_USER: nexususer
      POSTGRES_PASSWORD: nexuspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: nexus_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=nexusdb
      - POSTGRES_USER=nexususer
      - POSTGRES_PASSWORD=nexuspass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: deps
    container_name: nexus_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
